### PR TITLE
Fix TIMERs for Tasmota >= 9.4.0.5

### PR DESCRIPTION
**Pull request by barbudor**
Tasmota TIMERs messages has changed in 9.4.0.5.
as per discussion in https://github.com/jziolkowski/tdm/issues/151

This PR identifies the type of message and process accordingly the older and newer messages.

### CODE REVIEW

**Comment by jziolkowski** [comment]
Thanks for the PR.

Please remove comments, and bump TDM version to 0.2.11 so CI will build and publish properly

**Comment by barbudor** [comment]
You want me to remove ALL COMMENTS ?

**Comment by jziolkowski** [comment]
Pls remove commented out logging, and move the example timer payloads to function's docstring

**Comment by barbudor** [comment]
Done
Let's see if CI does the job 😉

**Comment by jziolkowski** [comment]
Thx

**Pull request merged**
